type Book @model {
  id: ID
  MediaTypeId: Int
  Name: String
  MediaDateTime: String
  MediaDateTimeVal: Int
  CategoryTags: String
  MenuTags: String
  AlbumTags: String
  Title: String
  Description: String
  People: String
  ToBeProcessed: Boolean
  SearchStr: String
  Selected: Boolean
}

type Board @model {
    id: ID
    TrusteeId: Int 
    Name: String
    Position: String
    PhoneNumber: String
    EmailAddress: String
    EmailAddressForward: String
    Description: String
    ImageUrl: String
}
